---
title: "Hong Kong and Macao Unsupervised Planning"
output: html_notebook
---

```{r}
require(readr)
require(dplyr)
require(geosphere)
require(ggplot2)
require(bbplot)
require(cluster)
require(ggmap)
```

# Parse XML
```{r}
# both functions are taken from https://gist.github.com/briatte/18a4d543d1ccca194b2a03ac512be2b4
kml_points <- function(x, layer = "d1", verbose = TRUE) {
  
  require(dplyr)
  require(stringr)
  require(xml2)
  
  #' Extract Placemark fields.
  #' 
  #' @param x A nodeset of Placemarks.
  #' @param field The name of the field to extract, e.g. \code{"name"}.
  #' @param layer The name of the layer to extract from; defaults to \code{"d1"}.
  #' @return A character vector. Missing values, i.e. empty fields, will be
  #' returned as \code{NA} values.
  get_field <- function(x, field, layer = "d1") {
    
    # vectorization required to get missing values when field is xml_missing
    lapply(x, xml_find_first, str_c(layer, ":", field)) %>%
      sapply(xml_text)
    
  }
  
  x <- read_xml(x) %>%
    xml_find_all(str_c("//", layer, ":Point/.."))
  
  x <- tibble(
    name = get_field(x, "name", layer),
    description = get_field(x, "description", layer),
    styleUrl = get_field(x, "styleUrl", layer),
    coordinates = get_field(x, str_c("Point/", layer, ":coordinates"), layer)
  )
  
  x$longitude <- kml_coordinate(x$coordinates, 1, verbose)
  x$latitude  <- kml_coordinate(x$coordinates, 2, verbose)
  x$altitude  <- kml_coordinate(x$coordinates, 3, verbose)
  
  return(select(x, -coordinates))
  
}

kml_coordinate <- function(x, coord, verbose = TRUE) {
  
  require(stringr) # includes `%>%`
  
  x <- str_replace(x, "(.*),(.*),(.*)", str_c("\\", coord)) %>%
    as.numeric
  
  if (verbose && coord == 1 && any(abs(x) > 180))
    message("Some longitudes are not contained within [-180, 180].")
  
  if (verbose && coord == 2 && any(abs(x) > 90))
    message("Some latitudes are not contained within [-90, 90].")
  
  if (verbose && coord == 3 && any(x < 0))
    message("Some altitudes are below sea level.")
  
  return(x)
  
}
```

```{r}
# modified version of usedist's package dist_make() function
# this function creates a dissimilarity matrix using haversine distance as dissimilarity metric
calculate_haversive_diss <- function (x, method = NULL) 
{
  distance_from_idxs <- function(idxs) {
    i1 <- idxs[1]
    i2 <- idxs[2]
    distHaversine(x[i1, ], x[i2, ], r = 6371)
  }
  size <- nrow(x)
  d <- apply(utils::combn(size, 2), 2, distance_from_idxs)
  attr(d, "Size") <- size
  xnames <- rownames(x)
  if (!is.null(xnames)) {
    attr(d, "Labels") <- xnames
  }
  attr(d, "Diag") <- FALSE
  attr(d, "Upper") <- FALSE
  if (!is.null(method)) {
    attr(d, "method") <- method
  }
  class(d) <- "dist"
  d
}
```

```{r}
raw <- read_file('~/Development/wanderdata-scripts/unsupervised-city-planning/hongkong/data/raw.kml')
df <- kml_points(raw)
coordinates <- df %>%
  select(longitude, latitude)
```

```{r}
distances <- calculate_haversive_diss(coordinates, distHaversine)
```

```{r}
coordinates.plot <- ggplot(coordinates, aes(x = longitude, y = latitude)) +
  geom_point() +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
      plot.margin = unit(c(1.0,1.0,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Coordinates scatterplot",
          subtitle = "Of locations from Hong Kong and Macau")
print(coordinates.plot)
```

```{r}
ggsave('plots/coordinates_plot.jpg', plot = coordinates.plot, 
           width = 15, height = 8, units = 'in')
```


```{r}
# diss is TRUE because we are using a dissimilarity matrix as input
p <- pam(distances, k = 9, diss = TRUE)
df$cluster <- as.factor(p$clustering)
df$isMedoid <- FALSE
df[p$medoids,]$isMedoid <- TRUE
```

```{r}
map <- get_googlemap(center=c(113.8629458, 22.2908493), zoom = 10, maptype = 'roadmap', size = c(640, 640), scale = 2)
```

```{r}
general.plot <- map %>% ggmap() +
  geom_point(data = df, 
             aes(x = df$longitude, y = df$latitude, color = df$cluster, size = 10)) +
  scale_color_brewer(palette = 'Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Hong Kong and Macau Planning Clusters", subtitle = "Where each cluster (color) represents one day")
print(general.plot)
```
```{r}
ggsave('plots/general_plot.jpg', plot = general.plot, 
           width = 15, height = 8, units = 'in')
```

```{r}
macau.map <- get_googlemap(center=c(113.5528549, 22.1791195),, zoom = 13, maptype = 'roadmap', size = c(640, 640), scale = 2) 
```

```{r}
macau.plot <- macau.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10)) +
  scale_color_brewer(palette='Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Macau Clusters", subtitle = "Where each cluster (color) represents one day")
print(macau.plot)
```

```{r}
ggsave('plots/macau_plot.jpg', plot = macau.plot, 
           width = 15, height = 8, units = 'in')
```

```{r}
macau.peninsula.map <- get_googlemap(center=c(113.5411517, 22.1974949),, zoom = 15, maptype = 'roadmap', size = c(640, 640), scale = 2, style = c(feature = 'all', element = 'labels', visibility = 'off')) 
```

```{r}
macau.plot.medoids <- macau.peninsula.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10, shape = isMedoid)) +
  scale_color_brewer(palette='Set1')+
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  guides(color = FALSE, size = FALSE) +
  ggtitle("Macau Clusters", subtitle = "Where each cluster (color) represents one day")
print(macau.plot.medoids)
```

```{r}
ggsave('plots/macau_plot_peninsula.jpg', plot = macau.plot, 
           width = 15, height = 8, units = 'in')
```

```{r}
hk.map <- get_googlemap(center=c(114.0835915, 22.3154898), zoom = 11, maptype = 'roadmap', size = c(640, 640), scale = 2) 
```

```{r}
hk.plot <- hk.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10)) +
  scale_color_brewer(palette='Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Hong Kong Clusters", subtitle = "Where each cluster (color) represents one day")
print(hk.plot)
```
```{r}
ggsave('plots/hk.jpg', plot = hk.plot, 
           width = 15, height = 8, units = 'in')
```

```{r}
kowloon.map <- get_googlemap(center=c(114.2029068, 22.33404660), zoom = 14, maptype = 'roadmap', size = c(640, 640), scale = 2) 
```

```{r}
kowloon.plot <- kowloon.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10)) +
  scale_color_brewer(palette='Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Kowloon Area Clusters", subtitle = "Where each cluster (color) represents one day")
print(kowloon.plot)
```

```{r}
ggsave('plots/kowloon.plot.jpg', plot = kowloon.plot, 
           width = 15, height = 8, units = 'in')
```

```{r}
hk.island.map <- get_googlemap(center=c(114.1724631, 22.26), zoom = 13, maptype = 'roadmap', size = c(640, 640), scale = 2, style = c(feature = "all", element = "labels", visibility = "off"),) 
```

```{r}
hk.island.plot <- hk.island.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10)) +
  scale_color_brewer(palette='Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Tsim Sha Tsui and Hong Kong Island Clusters", subtitle = 'Where each cluster (color) represents one day')
print(hk.island.plot)
```

```{r}
ggsave('plots/hk.island.plot.jpg', plot = hk.island.plot, 
           width = 15, height = 8, units = 'in')
```


```{r}
hk.island.plot.medoids <- hk.island.map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude, color = cluster, size = 10, shape = isMedoid)) +
  scale_color_brewer(palette='Set1')+
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  guides(color = FALSE, size = FALSE) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Tsim Sha Tsui and Hong Kong Island Clusters", subtitle = "Where each cluster (color) represents one day")
print(hk.island.plot.medoids)
```

```{r}
ggsave('plots/hk_island_medoids.jpg', plot = hk.island.plot.medoids, 
           width = 15, height = 8, units = 'in')
```

```{r}
print(p$clusinfo)
```

