---
title: "R Notebook"
output: html_notebook
---


```{r, include=FALSE}
require(ggplot2)
require(jsonlite)
require(maptools)
require(ggmap)
require(dplyr)
require(tidyr)
require(bbplot)
require(lubridate)
require(parsedate)
require(skimr)
require(tidyr)
require(ggcal)
require(gridExtra)
```

```{r}
## This function returns the timezone
determine.tz <- function(location) {
  switch (as.character(location),
    'SG' = return('Asia/Singapore'),
    'TH' = return('Asia/Bangkok'),
    'MY' = return('Asia/Kuala_Lumpur'),
    'JP' = return('Asia/Tokyo'),
    'HK' = return('Asia/Hong_Kong'),
  )
  
  return('Invalid')
}


extract.dateTime <- function(df, cc) {
  c.df <- df[df$venue.location.cc == cc,]
  c.df$dateTime <- as.character(as.POSIXct(c.df$createdAt,  origin="1970-01-01", tz=determine.tz(cc)))
  return(c.df)
}
```

```{r}
df <- fromJSON("data/checkins.json")

# json to dataframe
df <- flatten(df)
locations.df <- read.csv("~/Development/wanderdata-scripts/7-eleven-swarm/data/locations.csv", stringsAsFactors=FALSE)
locations.df$Date <- date(locations.df$Date)
```

```{r}
# create a new category column by select the category from the nested structure 'venue.category'
df$category <- sapply(df$venue.categories, function(x) x$name)
```

```{r}
convenience.stores <- df[df$category == 'Convenience Store',]
seven.elevens <- convenience.stores[grepl('7', convenience.stores$venue.name),]


jp.df <- extract.dateTime(seven.elevens, 'JP')
sg.df <- extract.dateTime(seven.elevens, 'SG')
hk.df <- extract.dateTime(seven.elevens, 'HK')
my.df <- extract.dateTime(seven.elevens, 'MY')
th.df <- extract.dateTime(seven.elevens, 'TH')

seven.elevens <- rbind(jp.df, sg.df, hk.df, my.df, th.df)
seven.elevens$posixct <- as.POSIXct(seven.elevens$dateTime)
seven.elevens$hour <- hour(seven.elevens$posixct)
seven.elevens$date <- date(seven.elevens$posixct)
seven.elevens$dateTimeNoSeconds <- format(seven.elevens$posixct, "%Y-%m-%d %H:%M")
seven.elevens$weekday <- weekdays(seven.elevens$posixct)
seven.elevens$weekday <- factor(seven.elevens$weekday, levels = c("Monday", "Tuesday", "Wednesday", "Thursday",  "Friday", 
                                                 "Saturday", "Sunday"))
```



# Visits per day
```{r}
visits.per.day <- seven.elevens %>%
  group_by(date) %>%
  summarise(n = n())

p <- ggplot(visits.per.day, aes(x = visits.per.day$n)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept=mean(visits.per.day$n)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(hjust = 1)) +
  ggtitle("Histogram of visits per day") +
  xlab('Visits') +
  ylab('Count')
print(p)
```

## Unique days
```{r}
length(visits.per.day$date)
# we need the percentage of days_with_711/days_total
```


# Visits per hour
```{r}
p <- ggplot(seven.elevens, aes(x = seven.elevens$hour)) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept=mean(seven.elevens$hour)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), "cm"),
        axis.text.x = element_text(hjust = 1)) +
  ggtitle("Visits per hour", subtitle = "From a sample of 99 visits") +
  xlab('Count') +
  ylab('Hour')
print(p)
ggsave('plots/visits_per_hour_hist.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

```{r}
p <- ggplot(seven.elevens, aes(x = 1, y = seven.elevens$hour)) +
  geom_violin() +
  geom_jitter(shape=16, position=position_jitter(0.2)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), "cm"),
        axis.text.x = element_text(hjust = 1)) +
  ggtitle("Visits per hour", subtitle = "From a sample of 99 visits") +
  xlab("Time")
print(p)
```

```{r}
locations <- unique(convenience.stores$venue.location.cc)
```

```{r}
df <- df[df$venue.location.cc %in% locations,]
```

## Summary

```{r}
## percentage of 7-11 Eleven checkins
(nrow(convenience.stores) / nrow(df)) * 100

# total checkins per location
checkins.location <- df %>%
  select(venue.location.cc) %>%
  group_by(venue.location.cc) %>%
  summarize(total_checkins = n())

se.checkins.location <- convenience.stores %>%
  select(venue.location.cc) %>%
  group_by(venue.location.cc) %>%
  summarize(se.checkins.location = n())

checkin.locations.df <- merge(checkins.location, se.checkins.location)
checkin.locations.df$percentage <- (checkin.locations.df$se.checkins.location / checkin.locations.df$total_checkins) * 100
```


```{r}
p <- ggplot(checkin.locations.df, aes(x=reorder(venue.location.cc, -se.checkins.location), y=se.checkins.location)) +
  geom_bar(aes(fill = venue.location.cc), stat = "identity") +
  scale_fill_brewer(palette="Set2") +
  labs(title="7-Eleven's check ins by country",
       subtitle = "From a sample of 99 visits") +
  xlab('Country') + ylab('Count') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
ggsave('plots/checkins_country.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

```{r}
p <- ggplot(checkin.locations.df, aes(x=reorder(venue.location.cc, -percentage), y=percentage)) +
  geom_bar(aes(fill = venue.location.cc), stat = "identity") +
  scale_fill_brewer(palette="Set2") +
  labs(title="Percentage of 7-Eleven's check ins by country",
       subtitle = "Compared to all the check ins") +
  xlab('Object') + ylab('Percentage') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
ggsave('plots/checkins_country_percentage.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```



```{r}
# Group by location
grouped.location <- convenience.stores %>%
  select(venue.id) %>%
  group_by(venue.id) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
print(grouped.location)
```



```{r}
p <- ggplot(grouped.location, aes(x = grouped.location$n)) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept=mean(grouped.location$n)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(hjust = 1)) +
  labs(title = "Visits per unique store",
       subtitle = "From a sample of 99 visits") +
  xlab('Visits') +
  ylab('Count')
print(p)
ggsave('plots/histogram.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

```{r}
frequency.table <- as.data.frame(table(grouped.location$n))
g <- tableGrob(frequency.table, rows = NULL, cols = c('Count', 'Freq'))
grid.arrange(g)
```

## Uniqueness
```{r}
unique(convenience.stores$venue.id)
```

```{r}
# Unique places by country
unique.per.country <- convenience.stores %>%
  select(venue.id, venue.location.cc) %>%
  group_by(venue.location.cc, venue.id) %>%
  summarise(n = n()) %>%
  group_by(venue.location.cc) %>%
  summarise(n = n()) %>%
  arrange(desc(n))


p <- ggplot(unique.per.country, aes(x=reorder(venue.location.cc, -n), y=n)) +
  geom_bar(aes(fill = venue.location.cc), stat = "identity") +
  scale_fill_brewer(palette="Set2") +
  labs(title="Unique visited 7-Eleven's by country",
       subtitle = "From a sample of 99 visits") +
  xlab('Country') + ylab('Country') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
ggsave('plots/unique_711.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```


## Maps

### Singapore
```{r}
singapore.summary <- sg.df %>%
  select(venue.id, venue.location.lat, venue.location.lng) %>%
  group_by(venue.id) %>%
  mutate(n = n()) %>%
  distinct(venue.id, .keep_all=TRUE)

# Singapore
sg.map <- get_googlemap(center = c(103.8481362, 1.3169034), zoom = 13, maptype = 'roadmap', size = c(640, 640), scale = 2,
                        style = c(feature = 'poi', element = 'labels', visibility = 'off')) 
```


```{r}
p <- sg.map %>% ggmap() +
  geom_point(data = singapore.summary, aes(venue.location.lng, venue.location.lat, fill = n), size=4, shape=21, stroke=2) +
  scale_fill_gradient(low='blue', high='red') +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle('7-Eleven check ins from Singapore', subtitle = '')
print(p)
ggsave('plots/sg_map.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

### Kuala Lumpur
```{r}
kl.summary <- my.df %>%
  select(venue.id, venue.location.lat, venue.location.lng) %>%
  group_by(venue.id) %>%
  mutate(n = n()) %>%
  distinct(venue.id, .keep_all=TRUE)

# Singapore
kl.map <- get_googlemap(center = c(101.7054197, 3.1467908), zoom = 15, maptype = 'roadmap', size = c(640, 640), scale = 2,
                        style = c(feature = 'poi', element = 'labels', visibility = 'off')) 
```



```{r, echo = T, results = 'hide'}
p <- kl.map %>% ggmap() +
  geom_point(data = kl.summary, aes(venue.location.lng, venue.location.lat, fill = n), size=4, shape=21, stroke=2) +
  scale_fill_gradient(low='blue', high='red') +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle('7-Eleven check ins from Kuala Lumpur (Malaysia)', subtitle = '')
print(p)
ggsave('plots/kl_map.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

### Malaysia
```{r}
my.summary <- my.df %>%
  select(venue.id, venue.location.lat, venue.location.lng) %>%
  group_by(venue.id) %>%
  mutate(n = n()) %>%
  distinct(venue.id, .keep_all=TRUE)

# Singapore
my.map <- get_googlemap(center = c(101.4180969, 3.5988685), zoom = 7, maptype = 'roadmap', size = c(640, 640), scale = 2,
                        style = c(feature = 'poi', element = 'labels', visibility = 'off')) 
```



```{r, echo = T, results = 'hide'}
p <- my.map %>% ggmap() +
  geom_point(data = kl.summary, aes(venue.location.lng, venue.location.lat, fill = n), size=4, shape=21, stroke=2) +
  scale_fill_gradient(low='blue', high='red') +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle('7-Eleven check ins from Malaysia', subtitle = '')
print(p)
ggsave('plots/my_map.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

### Japan


```{r}
tokyo.summary <- jp.df %>%
  select(venue.id, venue.location.lat, venue.location.lng) %>%
  group_by(venue.id) %>%
  mutate(n = n()) %>%
  distinct(venue.id, .keep_all=TRUE)

# Singapore
tokyo.map <- get_googlemap(center = c(139.7313031,35.6627282), zoom = 13, maptype = 'roadmap', size = c(640, 640), scale = 2,
                        style = c(feature = 'poi', element = 'labels', visibility = 'off')) 

```

```{r, echo = T, results = 'hide'}
p <- tokyo.map %>% ggmap() +
  geom_point(data = tokyo.summary, aes(venue.location.lng, venue.location.lat, fill = n), size=4, shape=21, stroke=2) +
  scale_fill_gradient(low='blue', high='red') +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle('7-Eleven check ins from Tokyo', subtitle = '')
print(p)
ggsave('plots/tokyo_map.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

### Thailand

```{r}
th.summary <- th.df %>%
  select(venue.id, venue.location.lat, venue.location.lng) %>%
  group_by(venue.id) %>%
  mutate(n = n()) %>%
  distinct(venue.id, .keep_all=TRUE)
```

```{r}
th.map <- get_googlemap(center = c(101.4412404, 16.7307649), zoom = 7, maptype = 'roadmap', size = c(640, 640), scale = 2,
                        style = c(feature = 'poi', element = 'labels', visibility = 'off')) 
```

```{r, echo = T, results = 'hide'}
p <- th.map %>% ggmap() +
  geom_point(data = th.summary, aes(venue.location.lng, venue.location.lat, fill = n), size=3, shape=21, stroke=1) +
  scale_fill_gradient(low='blue', high='red') +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle('7-Eleven check ins from Thailand', subtitle = '')
print(p)
ggsave('plots/th_map.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

## Correlation with steps

## Prepare time series data
```{r}
ts.df <- visits.per.day %>%
  select(date, n) %>%
  complete(date = seq.Date(min(date), max(date), by="day"))
```


```{r}
datetime.df <- tibble(ds = seven.elevens$dateTimeNoSeconds, y = 1)
ts.df <- datetime.df %>%
  select(ds, y) %>%
  complete(ds = as.character(format(seq(min(as.POSIXct("2019-08-04 00:00")), max(as.POSIXct("2019-12-15 23:59")),
                                        by="1 min"), "%Y-%m-%d %H:%M")))
ts.df[is.na(ts.df)] <- 0
colnames(ts.df) <- c('ds', 'y')
write.csv(ts.df, "ts_df.csv", row.names = FALSE)
```


## Calendar
```{r}
complete.visits.per.day <- visits.per.day %>%
  select(date, n) %>%
  complete(date = seq.Date(min(date), max(date), by='day'))
complete.visits.per.day[is.na(complete.visits.per.day)] <- 0
complete.visits.per.day$visited <- ifelse(complete.visits.per.day$n > 0, TRUE, FALSE)
complete.visits.per.day <- merge(complete.visits.per.day, locations.df, by.x = 'date', by.y = 'Date')
complete.visits.per.day$weekday <- weekdays(complete.visits.per.day$date)

p <- ggcal(complete.visits.per.day$date, complete.visits.per.day$visited) +
  scale_fill_discrete(na.value='gray70') +
  ggtitle("Days with visits to 7-Eleven") +
  theme(plot.margin = unit(c(1.0,1.0,1.0,0.5), "cm"),
        plot.title = element_text(family = 'Helvetica', size = 28, face = 'bold', color = '#222222'),
        axis.text = element_text(family = 'Helvetica', size = 18, color = '#222222'),
        strip.text.x = element_text(family = 'Helvetica', size = 14, color = '#222222', hjust=0, face='bold'))
print(p)
ggsave('plots/calendar.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

# Days spent in 7-Eleven countries
```{r}
nrow(complete.visits.per.day[complete.visits.per.day$CC %in%  c('SG', 'MY', 'HK', 'JP', 'TH'),])
```


```{r}
visits.weekday <- complete.visits.per.day %>%
  select(n, weekday) %>%
  group_by(weekday) %>%
  summarise(n = sum(n))

p <- ggplot(visits.weekday, aes(x=reorder(weekday, -n), y=n)) +
  geom_bar(aes(fill = weekday), stat = 'identity') +
  scale_fill_brewer(palette='Set2') +
  labs(title="Visits by day of the week") +
  xlab('Day') + ylab('Count') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        legend.position = 'none')
print(p)
ggsave('plots/visits_by_day.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```


```{r}
p <- ggplot(unique.per.country, aes(x=reorder(venue.location.cc, -n), y=n)) +
  geom_bar(aes(fill = venue.location.cc), stat = "identity") +
  scale_fill_brewer(palette="Set2") +
  labs(title="Unique visited 7-Eleven's by country",
       subtitle = "From a sample of 99 visits") +
  xlab('Country') + ylab('Country') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
```

```{r}
p <- ggplot(seven.elevens, aes(x = hour, y = weekday)) +
  geom_point() +
  scale_fill_brewer(palette="Set2") +
  labs(title="Unique visited 7-Eleven's by country",
       subtitle = "From a sample of 99 visits") +
  xlab('Country') + ylab('Country') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
```



## Locations with 7-11
```{r}
locations.with.se <- complete.visits.per.day[complete.visits.per.day$CC %in% locations,]
sum(locations.with.se$visited) / nrow(locations.with.se)
```


           
           
## Clustering
```{r}
dist_mat <- dist(seven.elevens$hour, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'average')
plot(hclust_avg)
rect.hclust(hclust_avg , k = 5, border = 2:4)
```

```{r}
cut_avg <- cutree(hclust_avg, k = 5)
plot(cut_avg, seven.elevens$hour)
```


```{r}
plot(hclust_avg)
rect.hclust(hclust_avg , h = 3, border = 2:4)
```

```{r}
cut_avg <- cutree(hclust_avg, k = 5)
clusters.values <- data.frame(cluster = cut_avg, hour = seven.elevens$hour)
clusters.values <- clusters.values %>% 
  select(cluster, hour) %>%
  group_by(cluster, hour) %>%
  mutate(n = n())

p <- ggplot(clusters.values, aes(x = cut_avg, y = seven.elevens$hour)) +
  geom_point(aes(size = n)) +
  labs(title="\"Visiting hours\" values per cluster") +
  xlab('Cluster') + ylab('Hour') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
ggsave('plots/hour_cluster.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

```{r}
p <- ggplot(clusters.values, aes(x = seven.elevens$weekday, y = seven.elevens$hour)) +
  geom_point(aes(size = n)) +
  labs(title="\"Visiting hours\" values and weekday") +
  xlab('Weekday') + ylab('Hour') +
  bbc_style() +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))
print(p)
print(p)
ggsave('plots/hours_weekdays.jpg', plot = p, 
           width = 15, height = 8, units = 'in')
```

```{r}
start.times <- select(seven.elevens, weekday, hour)
start.times$weekday <- as.numeric(start.times$weekday) - 1

start.times <- start.times %>%
  select(weekday, hour) %>%
  group_by(weekday, hour) %>%
  mutate(n = n())

write.csv(start.times, file = 'data/start_times.csv', row.names = FALSE)
```







