---
title: "R Notebook"
output: html_notebook
---


```{r}
setwd("~/Development/wanderdata-scripts/recap")

require(ggplot2)
require(bbplot)
require(skimr)
require(parsedate)
require(reshape2)
require(lubridate)
require(dplyr)
require(jsonlite)
require(tidyr)
require(scales)

data_dir <- 'data/'
plots_dir <- 'plots/'

first.date <- '2019-05-28'
last.date <- '2019-09-04'
```

```{r}
locations <- read.csv("~/Development/wanderdata-scripts/recap/locations.csv")
locations$posixct <-parse_date(locations$Date)
locations$dateTime <- date(locations$posixct)
locations$Country <- as.factor(locations$Country)
locations$Country <- factor(locations$Country, levels = c('Austria', 'Germany', 'Singapore', 'Malaysia',  'Thailand', 
                                                 'Cambodia'))
```


## Steps
```{r}
steps.df <- read.csv("~/Development/wanderdata-scripts/fitbit/data/steps.csv")
```


```{r}
steps.df$dateTime <- as.Date(steps.df$dateTime)
steps.df <- steps.df[steps.df$dateTime >= first.date & steps.df$dateTime <= last.date,]
steps.df <- left_join(steps.df, locations, by = 'dateTime')
print(skim(steps.df))
print(sum(steps.df$value))
print(sd(steps.df$value))

steps.df$Country <- factor(steps.df$Country, levels = c('Austria', 'Germany', 'Singapore', 'Malaysia',  'Thailand', 
                                                 'Cambodia'))
```


```{r}
p <- ggplot(steps.df, aes(x=dateTime, y=value, color=Country)) +
  geom_line(aes(group=1)) +
  geom_point() +
  scale_y_continuous(breaks = pretty_breaks()) +
  scale_x_date(date_labels = '%Y-%m-%d', date_breaks='1 week') +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(colour = guide_legend(nrow = 1)) +
  labs(title="My Fitbit's steps values",
       subtitle = sprintf("From %s until %s", first.date, last.date)) +
  ylab('Steps') +
  xlab('Value')

print(p)


ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "steps_plot", first.date, last.date), plot = p, 
       width = 12, height = 6, units = 'in')
```

```{r}
p <- ggplot(steps.df, aes(x=value)) +
  geom_histogram() +
  geom_vline(xintercept=mean(steps.df$value)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(hjust = 1)) +
  labs(title="Histogram of my Fitbit's steps",
       subtitle = sprintf("From %s until %s", first.date, last.date)) +
  ylab("Distance") +
  xlab('Value')

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "steps_histogram", first.date, last.date), plot = p, 
       width = 12, height = 6, units = 'in')
```


```{r}
distance.df <- read.csv("~/Development/wanderdata-scripts/fitbit/data/distance.csv")
distance.df$dateTime <- as.Date(distance.df$dateTime)
distance.df <- distance.df[distance.df$dateTime >= first.date & distance.df$dateTime <= last.date,]
distance.df <- left_join(distance.df, locations, by='dateTime')

p <- ggplot(distance.df, aes(x=dateTime, y=value, color=Country)) +
  geom_line(aes(group=1)) +
  geom_point() +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks='1 week') +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(colour = guide_legend(nrow = 1)) +
  labs(title="My Fitbit's distance (km) values",
       subtitle = sprintf("From %s until %s", first.date, last.date)) +
  ylab('Distance') +
  xlab('Value')

print(p)


ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "distance_plot", first.date, last.date), plot = p, 
       width = 12, height = 6, units = 'in')
```

```{r}
cor(steps.df$value, distance.df$value)
```


```{r}
barometer.df <- read.csv("~/Development/wanderdata-scripts/recap/data/barometer_background.csv", header = FALSE, stringsAsFactors = FALSE)
colnames(barometer.df) <- c('ts', 'value')
barometer.df$posixct <- parsedate::parse_date(barometer.df$ts)
barometer.df$dateTime <- date(barometer.df$posixct)
barometer.df$hour <- hour(barometer.df$posixct)
barometer.df <- barometer.df[barometer.df$date >= first.date & barometer.df$date < last.date,]
barometer.df <- left_join(barometer.df, locations, by='dateTime')
```


```{r}
summarized.barometer.df <- barometer.df %>%
      select(posixct.x, value, dateTime, hour, Country) %>%
      group_by(dateTime, hour) %>%
      summarise(median.barometer = median(value))
```


```{r}
weather.df <- read.csv("~/Development/wanderdata-scripts/weather/df.csv", stringsAsFactors = FALSE)
weather.df$posixct <- parsedate::parse_date(weather.df$dt)
weather.df$dateTime <- date(weather.df$posixct)
weather.df$hour <- hour(weather.df$posixct)
weather.df <- weather.df[weather.df$dateTime >= first.date & weather.df$dateTime < last.date,]
weather.df <- left_join(weather.df, locations, by='dateTime')
```

```{r}
weather.summarized.df <- weather.df %>%
      select(temp, dateTime, hour, Country) %>%
      group_by(dateTime, hour) %>%
      summarise(avg.temp = mean(temp))

weather.summarized.df <- left_join(weather.summarized.df, locations, by='dateTime')
weather.summarized.df$Location <- NULL
weather.summarized.df$region <- NULL
weather.summarized.df$Date <- NULL
weather.summarized.df$posixct <- NULL
weather.summarized.df$avg.temp <-weather.summarized.df$avg.temp - 273.15
weather.summarized.df$posixct <-as.POSIXct(paste0(weather.summarized.df$dateTime, ' ', weather.summarized.df$hour, ':00'), format="%Y-%m-%d %H:%M")

weather.summarized.df.no.de <- weather.summarized.df[weather.summarized.df$dateTime >= '2019-07-04' | weather.summarized.df$dateTime < '2019-06-29',]
```

```{r}
p <- ggplot(weather.summarized.df.no.de, aes(x = posixct, y = avg.temp, color = Country)) +
          geom_point(alpha = 0.5) +
          geom_smooth(linetype = 1, method = 'loess', span = 0.05, color = '#6d7d03') +
          scale_x_datetime(date_breaks = '1 week') +
          bbc_style() +
          theme(axis.title = element_text(size = 18), 
            plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
            axis.text.x = element_text(angle = 45, hjust = 1)) +
          guides(colour = guide_legend(nrow = 1)) +
          xlab('Date') + 
          ylab('Temperature') +
          labs(title="Average hourly temperature (°C)",
               subtitle = sprintf("From %s until %s", first.date, last.date))
          
print(p)
          
ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "temperature", first.date, last.date), plot = p, 
       width = 18, height = 8, units = 'in')
```

```{r}
weather.summarized.df <- inner_join(weather.summarized.df, summarized.barometer.df, by = c('dateTime', 'hour'))
```


```{r}
p <- ggplot(weather.summarized.df, aes(x=posixct, y=median.barometer, color=Country)) +
          geom_point(alpha = 0.5) +
          geom_smooth(linetype = 1, method = 'loess', span = 0.05, color = '#6d7d03') +
          scale_x_datetime(date_breaks='1 week') +
          labs(title=sprintf("%s value (%s) according to my phone", "Atmospheric Pressure", "hPa"),
               subtitle = sprintf("From %s until %s", first.date, last.date)) +
          xlab('Date') + 
          ylab('Pressure') +
          bbc_style() +
          theme(axis.title = element_text(size = 18), 
                    plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
                    axis.text.x = element_text(angle = 45, hjust = 1)) +
          guides(colour = guide_legend(nrow = 1)) 

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "hpa", first.date, last.date), plot = p, 
       width = 16, height = 8, units = 'in')
```


```{r}
# Pressure altitude, https://en.wikipedia.org/wiki/Pressure_altitude#cite_note-1
weather.summarized.df$pressureAltitude <- 145366.45 * (1- (weather.summarized.df$median.barometer/1013)^0.190284)
# convert from ft to m.
weather.summarized.df$pressureAltitude <- weather.summarized.df$pressureAltitude * 0.3048
```

```{r}
p <- ggplot() +
          geom_point(data=weather.summarized.df, aes(x=posixct, y=pressureAltitude, color=Country)) +
          geom_smooth(data=weather.summarized.df, aes(x=posixct, y=pressureAltitude), linetype = 1, method = 'loess', span = 0.05, color = '#6d7d03') +
          scale_x_datetime(date_breaks='1 week') +
          labs(title="Pressure altitude of visited places (in meters)",
               subtitle = sprintf("From %s until %s", first.date, last.date)) +
          xlab('Date') + 
          ylab('Pressure altitude') +
          bbc_style() +
          theme(axis.title = element_text(size = 18), 
                    plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
                    axis.text.x = element_text(angle = 45, hjust = 1)) +
          guides(colour = guide_legend(nrow = 1)) 

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "pressure_altitude", first.date, last.date), plot = p, 
       width = 16, height = 8, units = 'in')
```

```{r}
weather.summarized.df %>%
  select(pressureAltitude, Country) %>%
  group_by(Country) %>%
  summarize(n = median(pressureAltitude)) %>%
  arrange(desc(n))
```


#Instagram
```{r}
insta.df <- read.csv("~/Development/wanderdata-scripts/recap/data/insta_followers.csv", stringsAsFactors = FALSE)
insta.df <- insta.df[insta.df$dateTime >= first.date & insta.df$dateTime < last.date,]
insta.df$posixct <- parsedate::parse_date(insta.df$dateTime)
insta.df <- insta.df %>%
  select(posixct, value) %>%
  group_by(posixct) %>%
  summarize(value=max(value))
  
```

```{r}
p <- ggplot(insta.df, aes(x=posixct, y=value)) +
          geom_point(alpha = 0.3) +
          geom_smooth(linetype = 1, method = 'loess', span = 0.5, color = '#6d7d03') +
          bbc_style() +
          scale_x_datetime(date_breaks='1 week') +
          theme(axis.title = element_text(size = 18), 
                plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
                axis.text.x = element_text(angle = 45, hjust = 1)) +
          guides(colour = guide_legend(nrow = 1)) +
          labs(title="Number of Instagram followers",
               subtitle = sprintf("From %s until %s", first.date, last.date)) +
          ylab('Followers') +
          xlab('Date')
print(p)
```

# Swarm
```{r}
swarm.df <- jsonlite::fromJSON('~/Development/wanderdata-scripts/swarmapp/data/checkins.json')

# json to dataframe
swarm.df <- flatten(swarm.df)

# create a new category column by select the category from the nested structure 'venue.category'
# swarm.df$category <- sapply(swarm.df$venue.categories, function(x) unlist(x)[2][[1]])
swarm.df$posixct <- parsedate::parse_date(swarm.df$createdAt)
swarm.df$dateTime <- date(swarm.df$posixct)
swarm.df$hour <- hour(swarm.df$posixct)
```

```{r}
checkin.days <- swarm.df %>%
  select(dateTime) %>%
  group_by(dateTime) %>%
  summarize(n = n()) %>%
  complete(dateTime = seq.Date(min(dateTime), max(dateTime), by = 'day'))

checkin.days[is.na(checkin.days)] <- 0
checkin.days <- left_join(checkin.days, locations, by='dateTime')

p <- ggplot(checkin.days, aes(x=dateTime, y=n, color=Country)) +
  geom_line(aes(group=1)) +
  geom_point() +
  scale_x_date(date_labels = '%Y-%m-%d', date_breaks='1 week') +
  scale_y_continuous(breaks= pretty_breaks()) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(colour = guide_legend(nrow = 1)) +
  labs(title="Number of Swarm's check-ins",
       subtitle = sprintf("From %s until %s", first.date, last.date)) +
  ylab("Check-ins") +
  xlab("Date")


print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "swarm_checkins", first.date, last.date), plot = p, 
       width = 16, height = 8, units = 'in')
```


```{r}
categories <- data.frame(category = character())
for (i in 1:nrow(swarm.df)) {
  if (length(swarm.df[i,]$venue.categories[[1]]) == 0) {
    categories <- rbind(categories, 'Undefined')
  } else {
    categories <- rbind(categories, swarm.df[i,]$venue.categories[[1]][2])
  }
}


swarm.df$category <- categories$name
top.categories <- swarm.df %>%
  select(category) %>%
  group_by(category) %>%
  summarise(n = n()) %>%
  arrange(n, desc(n)) %>%
  mutate(percentage=(n/nrow(.)) * 100)

p <- ggplot(top.categories[top.categories$n > 3,], aes(x = reorder(category, -n), y = n)) +
  geom_bar(stat = 'identity') +
  bbc_style() +
  ggtitle("My check-ins categories",
          subtitle=sprintf("From Swarm's check-ins created from %s until %s", first.date, last.date))+
  xlab("Category") +
  ylab("Check-ins") +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
        axis.text.x = element_text(hjust = 1, angle = 45, size = 20),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) +
  guides(colour = guide_legend(nrow = 1)) 

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "check_ins_categories", first.date, last.date), plot = p, 
       width = 16, height = 9, units = 'in')
```


```{r}
top.categories.hour <- swarm.df %>%
  select(category, hour) %>%
  group_by(category) %>%
  mutate(n = n()) %>%
  arrange(n, desc(n))
```

```{r}
p <- ggplot(top.categories.hour[top.categories.hour$n > 5,], aes(factor(category), hour)) +
  geom_violin() +
  scale_y_continuous(breaks= pretty_breaks(n = 10)) +
  ggtitle("Check-in times of my top categories",
          subtitle=sprintf("From Swarm's check-ins created from %s until %s", first.date, last.date)) +
  bbc_style() +
  xlab('Category') +
  ylab('Hour') +
  theme(axis.title = element_text(size = 24), 
        plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 18),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "checkins_times", first.date, last.date), plot = p, 
       width = 16, height = 8, units = 'in')
```


## Spotify
```{r}
spotify.df <- read.csv("~/Development/wanderdata-scripts/spotify/data/df.csv", stringsAsFactors=FALSE)
spotify.df$posixct <-parsedate::parse_date(spotify.df$PlayedAt)
spotify.df$posixct <- with_tz(spotify.df$posixct, 'UTC')
spotify.df$dateTime <- as.Date(spotify.df$posixct)
spotify.df <- spotify.df[spotify.df$dateTime >= first.date & spotify.df$dateTime <= last.date,]
spotify.df <- left_join(spotify.df, locations, by = 'dateTime')

determine.tz <- function(location) {
  switch (as.character(location),
    'Germany' = return('CET'),
    'Austria' = return('CET'),
    'Singapore' = return('Asia/Singapore'),
    'Thailand' = return('Asia/Bangkok'),
    'Malaysia' = return('Asia/Kuala_Lumpur'),
    'Cambodia' = return('Asia/Phnom_Penh'),
  )
  
  return('Invalid')
}

z <- spotify.df %>%
  rowwise() %>%
  do(local.posixct = with_tz(.$posixct.x, tzone = determine.tz(.$Country)))

spotify.df$local.posixct <- parsedate::parse_date(z$local.posixct)
spotify.df$date <- date(spotify.df$local.posixct)
```

```{r}
# songs per day
songs.by.day <- spotify.df %>%
  group_by(date) %>%
  summarise(n = n()) %>%
  complete(date = seq.Date(min(date), max(date), by = 'day'))
songs.by.day[is.na(songs.by.day)] <- 0
```


```{r}
print(skim(songs.by.day))
print(sum(songs.by.day$n))
```


```{r}
p <- ggplot(data=songs.by.day, aes(x = date, y = n)) +
  geom_line(linetype = 1, color = '#6d7d03') +
  geom_point() +
  scale_x_date(date_labels = '%Y-%m-%d', date_breaks='1 week') +
  bbc_style() +
  labs(title="Number of songs I played on Spotify",
       subtitle = sprintf("From %s until %s", first.date, last.date)) +
  xlab('Date') + 
  ylab('Value') +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.5, 1.0, 1.0), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) +
  guides(colour = guide_legend(nrow = 1)) 

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir,'played_songs', first.date, last.date), plot = p, 
       width = 12, height = 6.82, units = 'in')
```


```{r}
top.artists <- spotify.df %>%
  group_by(MainArtistName) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  mutate(percentage=(n/nrow(spotify.df)) * 100)

print(head(top.artists))

```

```{r}
p <- ggplot(head(top.artists, n=10), aes(x=reorder(MainArtistName, -n), y = n)) + 
    geom_bar(stat='identity') +
    bbc_style() +
    theme(axis.title = element_text(size = 18), 
          plot.margin = unit(c(1.5, 1.5, 1.5, 1.5), 'cm'),
          axis.text.x = element_text(angle = 45, hjust = 1)) +
          guides(colour = guide_legend(nrow = 1)) +
    labs(title="My top 10 most played artists on Spotify",
         subtitle = sprintf("From %s until %s", first.date, last.date)) +
    ylab('Number of songs') +
    xlab('Artist')
  
print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir,"top_artists", first.date, last.date), plot = p, 
       width = 15, height = 9, units = 'in')
```


```{r}
# top songs
spotify.df$SongAndArtist <- sprintf('%s (%s)', spotify.df$Name, spotify.df$MainArtistName)
top.songs <- spotify.df %>%
  group_by(SongAndArtist) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  mutate(percentage = (n/nrow(spotify.df)) * 100)

print(head(top.songs, n = 10))
```

```{r}
p <- ggplot(head(top.songs, n=15), aes(x=reorder(SongAndArtist, -n), y = n)) + 
    geom_bar(stat = 'identity') +
    bbc_style() +
    theme(axis.title = element_text(size = 18), 
          plot.margin = unit(c(2.0, 2.0, 2.0, 2.5), 'cm'),
          axis.text.x = element_text(angle = 45, hjust = 1, size = 14)) +
    labs(title="My top 10 most played songs on Spotify",
         subtitle = sprintf("From %s until %s", first.date, last.date)) +
    ylab('Number of reproductions') +
    xlab('Song')

print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir,"top_songs", first.date, last.date), plot = p, 
       width = 18, height = 12, units = 'in')
```


# Sleep
```{r}
sleep.df <- read.csv("~/Development/wanderdata-scripts/fitbit/data/sleep.csv", stringsAsFactors = FALSE)
sleep.df$dateTime <- date(sleep.df$date)
sleep.df <- sleep.df[sleep.df$dateTime >= first.date & sleep.df$dateTime <= last.date,]
sleep.df <- left_join(sleep.df, locations, by = 'dateTime')
```

```{r}
sleep.df %>%
  group_by(Country) %>%
  summarise(n = mean(minutesAsleep)/60)
```


```{r}
p <- ggplot(sleep.df, aes(x = dateTime, y = minutesAsleep/60, color = Country)) +
  geom_line(aes(group=1)) +
  geom_point() +
  scale_x_date(date_labels = '%Y-%m-%d', date_breaks = '1 week') +
  scale_y_continuous(breaks = pretty_breaks(n = 10)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), 'cm'),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title="My minutes asleep according to Fitbit",
         subtitle = sprintf("From %s until %s", first.date, last.date)) +
  guides(colour = guide_legend(nrow = 1)) +
  ylab('Hours') +
  xlab('Date') 


print(p)

ggsave(sprintf("%s%s_%s_%s.jpg", plots_dir, "minutes_asleep.jpg", first.date, last.date), plot = p, 
       width = 16, height = 9, units = 'in')
```




